image: nexus.asta.ir:4000/docker

stages:
  - build

build:
  stage: build
  script:
    - docker build . -t nexus.asta.ir:4000/im/maven-graphics-magick:3.6.1-jdk-8
    - docker push  nexus.asta.ir:4000/im/maven-graphics-magick
